.POSIX:

.SUFFIXES:

1_1: 1_1.swift
	swiftc $^

1_2: 1_2.swift
	swiftc $^

2_1: 2_1.swift
	swiftc $^

2_2: 2_2.swift
	swiftc $^

3_1: 3_1.swift
	swiftc $^

3_2: 3_2.swift
	swiftc $^

4_1: 4_1.swift
	swiftc $^

# 4_2: 4_2.swift
# 	swiftc $^

all: 1_1 1_2 2_1 2_2 3_1 3_2 4_1 #4_2

.PHONY: all
