.POSIX:

.SUFFIXES:

SWIFT_FLAGS := -g -O

1_1: 1_1.swift
	swiftc $^ $(SWIFT_FLAGS)

1_2: 1_2.swift
	swiftc $^ $(SWIFT_FLAGS)

2_1: 2_1.swift
	swiftc $^ $(SWIFT_FLAGS)

2_2: 2_2.swift
	swiftc $^ $(SWIFT_FLAGS)

3_1: 3_1.swift
	swiftc $^ $(SWIFT_FLAGS)

3_2: 3_2.swift
	swiftc $^ $(SWIFT_FLAGS)

4_1: 4_1.swift
	swiftc $^ $(SWIFT_FLAGS)

4_2: 4_2.swift
	swiftc $^ $(SWIFT_FLAGS)

5_1: 5_1.swift
	swiftc $^ $(SWIFT_FLAGS)

5_2: 5_2.swift
	swiftc $^ $(SWIFT_FLAGS)

6_1: 6_1.swift
	swiftc $^ $(SWIFT_FLAGS)

6_2: 6_2.swift
	swiftc $^ $(SWIFT_FLAGS)

7_1: 7_1.swift
	swiftc $^ $(SWIFT_FLAGS)

7_2: 7_2.swift
	swiftc $^ $(SWIFT_FLAGS)

8_1: 8_1.swift
	swiftc $^ $(SWIFT_FLAGS)

8_2: 8_2.swift
	swiftc $^ $(SWIFT_FLAGS)

all: 1_1 1_2 2_1 2_2 3_1 3_2 4_1 4_2 5_1 5_2 6_1 6_2 7_1 7_2 8_1 8_2

.PHONY: all
